# Jekyll
title: Sterling Consulting
email: inquiry@sterling-consulting.net
description: Marketing and Project Management Consultants
baseurl: "/sterling-consulting" # the subpath of your site, e.g. /blog
url: "http://www.sterling-consulting.net" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: droualdes
# github_username:  droualdes
exclude: [ '_site/', '_ignore/']

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
